# Generated by Django 3.2.12 on 2022-03-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
    ]
