# Generated by Django 3.2.12 on 2022-03-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_auth', '0003_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_auth_secret',
            field=models.CharField(default='', max_length=255),
        ),
    ]
